### PR TITLE
refactor Pipfile.find

### PR DESCRIPTION
**Pull request by ofek**

### CODE REVIEW

**Comment by ofek** [comment]
@kennethreitz Ready for review :)

**Comment by kennethreitz** [comment]
this looks great! would like to test it manually first.

**Comment by kennethreitz** [comment]
but i'll trust that it works :)

**Comment by kennethreitz** [comment]
this actually breaks pipenv functionality

**Comment by ofek** [comment]
What did it break?

**Comment by ofek** [comment]
Ah sorry, the os.walk topdown=False docs are very misleading. Yes please revert :/

**Comment by kennethreitz** [comment]
No worries :)

**Comment by edbennett** [comment]
This doesn't seem to have been reverted? (I was just looking through the old version of the code installed on my machine, also thought it would benefit from refactoring, so came to look at the current version of the code and found it broken...)

**Pull request merged**
